### PR TITLE
Chamodhk patch 1

### PR DESCRIPTION
**Pull request by chamodhk**
Hi Mate,

I tried to improve your code. Please review and merge my pull request.

### CODE REVIEW

**Comment by mendisofficial** [comment]
So what is the improvement of this using a for loop?

**Comment by chamodhk** [comment]
The original code doesn't work as intended. Just modified the code so that it works as expected.

**Comment by chamodhk** [comment]
Nothing special with the for loop

**Comment by mendisofficial** [comment]
This is a simple program just to fulfill some of my personal issues. So the original program works for me as I expected. What are the problems that you are facing with the original code?

**Comment by chamodhk** [comment]
The countdown feature is not working as intended. However,  I cannot test it right now. Will get back to you when I have access to my pc

**Pull request closed without merging**
